name: Tikube CI/CD Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main # Ensure this job runs only on pushes to main branch

jobs:
  test_and_quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21'

      # Install golint
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      # Run golint
      - name: Run golint
        run: golint -set_exit_status ./...

      # Install staticcheck
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      # Run staticcheck
      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./... -v

  build_and_push:
    needs: test_and_quality_check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Condition to run only on push to main
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jmartin1/tikube:latest
